### Create User
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "thebigyovadiaz",
  "password": "1234567890"
}

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "yovadiaz",
  "password": "123456"
}
